name: Security Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Syft
        run: |
          curl -sSL https://github.com/anchore/syft/releases/download/v0.64.0/syft-linux-amd64 -o /usr/local/bin/syft
          chmod +x /usr/local/bin/syft

      - name: Run Syft Scan
        run: syft .

      - name: Install Semgrep
        run: |
          curl -sL https://github.com/returntocorp/semgrep/releases/latest/download/semgrep-linux -o semgrep
          chmod +x semgrep
          mv semgrep /usr/local/bin/

      - name: Run Semgrep Scan
        run: semgrep --config=auto .

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/zricethezav/gitleaks/releases/download/v8.9.0/gitleaks-linux-amd64 -o /usr/local/bin/gitleaks
          chmod +x /usr/local/bin/gitleaks

      - name: Run Gitleaks Scan
        run: gitleaks detect --source=. --verbose

      - name: Install OWASP ZAP
        run: |
          curl -sL https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Linux.tar.gz | tar -xz
          sudo mv ZAP_2.11.1 /opt/zap

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'https://owasp-juice.shop'
          fail_action: false

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: security-reports
          path: |
            report_json.json
            report_md.md
            report_html.html
